# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-26 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAuthor',
            fields=[
                ('author_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('author_username', models.CharField(max_length=150)),
                ('author_first_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(max_length=30)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DimCategory',
            fields=[
                ('category_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DimCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField()),
                ('course_name', models.CharField(max_length=120)),
                ('course_pub_date', models.DateField()),
                ('platform_name', models.CharField(blank=True, max_length=120)),
                ('platform_url', models.URLField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.DimAuthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.DimCategory')),
            ],
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('month', models.CharField(max_length=16)),
                ('year', models.PositiveSmallIntegerField()),
                ('month_of_year', models.PositiveSmallIntegerField()),
                ('week_of_year', models.PositiveSmallIntegerField()),
                ('day_of_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField()),
                ('student_username', models.CharField(max_length=150)),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FactCabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_id', models.PositiveIntegerField()),
                ('likes_count', models.PositiveIntegerField()),
                ('students_count', models.PositiveIntegerField()),
                ('dim_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.DimCourse')),
                ('dim_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.DimDate')),
                ('dim_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.DimStudent')),
            ],
        ),
    ]
