# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='public_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
