# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='public_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo_url',
            field=models.URLField(default='http://res.cloudinary.com/dzmnskqms/image/upload/v1495731762/unknown_swxwii.png'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo_url',
            field=models.URLField(default='http://res.cloudinary.com/dzmnskqms/image/upload/v1495731762/unknown_swxwii.png'),
        ),
    ]
