# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_course_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
